# This is a basic workflow to help you get started with Actions

name: Build and Create Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "SCRIPTS_PATH=scripting" >> $GITHUB_ENV
          mkdir plugins

      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@v1.2.4
        with:
          # Version of SP compiler
          version: 1.10.x

      - name: Compile EventQueueFix
        run:
            spcomp -E -w234 -O2 -v2 -i include -o ../plugins/eventqueuefix.smx eventqueuefix.sp
        working-directory: ${{ env.SCRIPTS_PATH }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: eventqueuefix-dev
          path: |
                .
                !.github
                !.git
                !.gitattributes
